[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "Space Mono"
style = "Bold"

[font.bold_italic]
family = "Space Mono"
style = "Bold Italic"

[font.italic]
family = "Space Mono"
style = "Italic"

[font.normal]
family = "Space Mono"
style = "Regular"

[window]
opacity = 0.9

# BEGIN ACE
[colors]
indexed_colors = [{ index = 16, color = "0x222222"}]

# Primary colors
[colors.primary]
background = "#222222"
foreground = "#c2c2b0"

# Normal colors
[colors.normal]
black = "#222222"
red = "#685742"
green = "#5f875f"
yellow = "#b36d43"
blue = "#78824b"
magenta = "#bb7744"
cyan = "#c9a554"
white = "#d7c483"

# Bright colors
[colors.bright]
black = "#666666"
red = "#685742"
green = "#5f875f"
yellow = "#b36d43"
blue = "#78824b"
magenta = "#bb7744"
cyan = "#c9a554"
white = "#d7c483"
# END ACE

