#!/bin/bash

OUTPUT="/home/daif/Videos/GIF-$(date '+%F-%H').gif"

wf-recorder -g "$(slurp)" -f ~/Videos/recording.mkv

ffmpeg -i ~/Videos/recording.mkv -vf "fps=10,scale=640:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" -loop 0 "${OUTPUT}"

rm ~/Videos/recording.mkv
